[workspace]
members = ["cargo:."]

# Config for 'dist'
[dist]
# Skip checking whether the specified configuration files are up to date
allow-dirty = ["ci"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell", "homebrew"]
# A GitHub repo to push Homebrew formulas to
tap = "stevedylandev/homebrew-walletfetch"
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Publish jobs to run in CI
publish-jobs = ["homebrew"]
# Whether to install an updater program
install-updater = false

# Custom runner configurations
[dist.github-custom-runners]
# Use Ubuntu 24.04 for Linux builds
x86_64-unknown-linux-gnu = "ubuntu-24.04"
aarch64-unknown-linux-gnu = "ubuntu-24.04"
# Use Windows 2022 for Windows builds (this is already the default, but explicitly specified here)
x86_64-pc-windows-msvc = "windows-2022"
